stages:
  - lint
  - build_image
  - deploy

lint:
  stage: lint
  image: python:3.11
  before_script:
    - apt update
    - apt install make
    - make venv
  script:
    - make lint

.build_image_base:
  stage: build_image
  image: docker:20
  variables:
    IMAGE_NAME: ""
  services:
    - name: docker:20-dind
      variables:
        DOCKER_TLS_CERTDIR: ""
  script:
    - echo ${CI_REGISTRY}
    - echo ${CI_REGISTRY_IMAGE}
    - echo ${IMAGE_NAME}
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build -t ${IMAGE_NAME} -f deployments/app/Dockerfile .
    - docker push ${IMAGE_NAME}
  when: manual
  allow_failure: false

build_image_test:
  extends: .build_image_base
  variables:
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}-test

build_image_prod:
  extends: .build_image_base
  variables:
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}-prod
  only:
    - tags

deploy_test:
  stage: deploy
  variables:
    UPSTREAM_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}-test
    UPSTREAM_PROJECT: "turlalead_backend"
    UPSTREAM_ENVIRONMENT: "test"
  trigger:
    project: team-shining-departure/swarm-deploy
  needs:
    - build_image_test

deploy_prod:
  stage: deploy
  variables:
    UPSTREAM_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}-prod
    UPSTREAM_PROJECT: "turlalead_backend"
    UPSTREAM_ENVIRONMENT: "prod"
  trigger:
    project: team-shining-departure/swarm-deploy
  needs:
    - build_image_prod
  only:
    - tags
